- name: add the EPEL and remi repository
  package:
    name:  
      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      - http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present
- name: install yum-utils
  yum:
    name:  yum-utils
    state: present
- name: enable remi to install php5.6
  command: 
  cmd: yum-config-manager --enable remi-php56 
- name: install php 
  package:
    name: 
      - php
      -  php-mcrypt
      -  php-cli
      -  php-gd php-curl
      -  php-mysql 
      - php-ldap 
      - php-zip 
      - php-fileinfo
    state: present 
